//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestMustekImportService.MustekOrders {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Response", Namespace="http://schemas.datacontract.org/2004/07/OrderImportService")]
    [System.SerializableAttribute()]
    public partial class Response : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResponseMsgField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool WasSuccessFullField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResponseMsg {
            get {
                return this.ResponseMsgField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseMsgField, value) != true)) {
                    this.ResponseMsgField = value;
                    this.RaisePropertyChanged("ResponseMsg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool WasSuccessFull {
            get {
                return this.WasSuccessFullField;
            }
            set {
                if ((this.WasSuccessFullField.Equals(value) != true)) {
                    this.WasSuccessFullField = value;
                    this.RaisePropertyChanged("WasSuccessFull");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MustekOrders.IOrders")]
    public interface IOrders {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrders/PostOrder", ReplyAction="http://tempuri.org/IOrders/PostOrderResponse")]
        TestMustekImportService.MustekOrders.Response PostOrder(string xmlData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrders/PostOrder", ReplyAction="http://tempuri.org/IOrders/PostOrderResponse")]
        System.Threading.Tasks.Task<TestMustekImportService.MustekOrders.Response> PostOrderAsync(string xmlData);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOrdersChannel : TestMustekImportService.MustekOrders.IOrders, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OrdersClient : System.ServiceModel.ClientBase<TestMustekImportService.MustekOrders.IOrders>, TestMustekImportService.MustekOrders.IOrders {
        
        public OrdersClient() {
        }
        
        public OrdersClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OrdersClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrdersClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrdersClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TestMustekImportService.MustekOrders.Response PostOrder(string xmlData) {
            return base.Channel.PostOrder(xmlData);
        }
        
        public System.Threading.Tasks.Task<TestMustekImportService.MustekOrders.Response> PostOrderAsync(string xmlData) {
            return base.Channel.PostOrderAsync(xmlData);
        }
    }
}
