//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18033.
// 
#pragma warning disable 1591

namespace TariffCodeCCLValidation.Service {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ProgramCallPortBinding", Namespace="http://ws.cc.com/")]
    public partial class ProgramCallService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback callCCL9010OperationCompleted;
        
        private System.Threading.SendOrPostCallback callProgramOperationCompleted;
        
        private System.Threading.SendOrPostCallback getPcmlDocumentOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ProgramCallService() {
            this.SoapVersion = System.Web.Services.Protocols.SoapProtocolVersion.Soap12;
            this.Url = global::TariffCodeCCLValidation.Properties.Settings.Default.TariffCodeCCLValidation_Service1_ProgramCallService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event callCCL9010CompletedEventHandler callCCL9010Completed;
        
        /// <remarks/>
        public event callProgramCompletedEventHandler callProgramCompleted;
        
        /// <remarks/>
        public event getPcmlDocumentCompletedEventHandler getPcmlDocumentCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://ws.cc.com/", ResponseNamespace="http://ws.cc.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ccl9010 callCCL9010(ccl9010 ccl9010) {
            object[] results = this.Invoke("callCCL9010", new object[] {
                        ccl9010});
            return ((ccl9010)(results[0]));
        }
        
        /// <remarks/>
        public void callCCL9010Async(ccl9010 ccl9010) {
            this.callCCL9010Async(ccl9010, null);
        }
        
        /// <remarks/>
        public void callCCL9010Async(ccl9010 ccl9010, object userState) {
            if ((this.callCCL9010OperationCompleted == null)) {
                this.callCCL9010OperationCompleted = new System.Threading.SendOrPostCallback(this.OncallCCL9010OperationCompleted);
            }
            this.InvokeAsync("callCCL9010", new object[] {
                        ccl9010}, this.callCCL9010OperationCompleted, userState);
        }
        
        private void OncallCCL9010OperationCompleted(object arg) {
            if ((this.callCCL9010Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.callCCL9010Completed(this, new callCCL9010CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://ws.cc.com/", ResponseNamespace="http://ws.cc.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public programCallResult callProgram(authenticationData authData, string program, string pcmlDocument) {
            object[] results = this.Invoke("callProgram", new object[] {
                        authData,
                        program,
                        pcmlDocument});
            return ((programCallResult)(results[0]));
        }
        
        /// <remarks/>
        public void callProgramAsync(authenticationData authData, string program, string pcmlDocument) {
            this.callProgramAsync(authData, program, pcmlDocument, null);
        }
        
        /// <remarks/>
        public void callProgramAsync(authenticationData authData, string program, string pcmlDocument, object userState) {
            if ((this.callProgramOperationCompleted == null)) {
                this.callProgramOperationCompleted = new System.Threading.SendOrPostCallback(this.OncallProgramOperationCompleted);
            }
            this.InvokeAsync("callProgram", new object[] {
                        authData,
                        program,
                        pcmlDocument}, this.callProgramOperationCompleted, userState);
        }
        
        private void OncallProgramOperationCompleted(object arg) {
            if ((this.callProgramCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.callProgramCompleted(this, new callProgramCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://ws.cc.com/", ResponseNamespace="http://ws.cc.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public programCallResult getPcmlDocument(authenticationData authData, string program) {
            object[] results = this.Invoke("getPcmlDocument", new object[] {
                        authData,
                        program});
            return ((programCallResult)(results[0]));
        }
        
        /// <remarks/>
        public void getPcmlDocumentAsync(authenticationData authData, string program) {
            this.getPcmlDocumentAsync(authData, program, null);
        }
        
        /// <remarks/>
        public void getPcmlDocumentAsync(authenticationData authData, string program, object userState) {
            if ((this.getPcmlDocumentOperationCompleted == null)) {
                this.getPcmlDocumentOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetPcmlDocumentOperationCompleted);
            }
            this.InvokeAsync("getPcmlDocument", new object[] {
                        authData,
                        program}, this.getPcmlDocumentOperationCompleted, userState);
        }
        
        private void OngetPcmlDocumentOperationCompleted(object arg) {
            if ((this.getPcmlDocumentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getPcmlDocumentCompleted(this, new getPcmlDocumentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18033")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.cc.com/")]
    public partial class ccl9010 {
        
        private authenticationData aUTHDATAField;
        
        private dccl9010V bEDATAField;
        
        private dccl9010 dATAField;
        
        private dccl9010R rETURNDTAField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public authenticationData AUTHDATA {
            get {
                return this.aUTHDATAField;
            }
            set {
                this.aUTHDATAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public dccl9010V BEDATA {
            get {
                return this.bEDATAField;
            }
            set {
                this.bEDATAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public dccl9010 DATA {
            get {
                return this.dATAField;
            }
            set {
                this.dATAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public dccl9010R RETURNDTA {
            get {
                return this.rETURNDTAField;
            }
            set {
                this.rETURNDTAField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18033")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.cc.com/")]
    public partial class authenticationData {
        
        private string agentField;
        
        private string keyField;
        
        private string passwordField;
        
        private string userField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string agent {
            get {
                return this.agentField;
            }
            set {
                this.agentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string user {
            get {
                return this.userField;
            }
            set {
                this.userField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18033")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.cc.com/")]
    public partial class programCallResult {
        
        private string errorField;
        
        private bool executedField;
        
        private string pcmlDocumentField;
        
        private string programField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool executed {
            get {
                return this.executedField;
            }
            set {
                this.executedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string pcmlDocument {
            get {
                return this.pcmlDocumentField;
            }
            set {
                this.pcmlDocumentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string program {
            get {
                return this.programField;
            }
            set {
                this.programField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18033")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.cc.com/")]
    public partial class dccl9010R {
        
        private string[] aMSGField;
        
        private string aTVVALUEField;
        
        private string s1P1DUTYField;
        
        private string s1P2ACODEField;
        
        private string s1P2ADUTYField;
        
        private string s1P2BDUTYField;
        
        private string s1P3ACODEField;
        
        private string s1P3ADUTYField;
        
        private string s1P3BCODEField;
        
        private string s1P3BDUTYField;
        
        private string s1P3CCODEField;
        
        private string s1P3CDUTYField;
        
        private string s1P3DCODEField;
        
        private string s1P3DDUTYField;
        
        private string s1P5ADUTYField;
        
        private string s1P5BDUTYField;
        
        private string s2P1DUTYField;
        
        private string s2P1DUTYCODEField;
        
        private string s2P2DUTYField;
        
        private string s2P2DUTYCODEField;
        
        private string s2P3DUTYField;
        
        private string s2P3DUTYCODEField;
        
        private string sUCCESField;
        
        private string tOTALDUEField;
        
        private string tOTALDUTIESField;
        
        private string vATVALUEField;
        
        private string wCUSVALField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AMSG", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] AMSG {
            get {
                return this.aMSGField;
            }
            set {
                this.aMSGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ATVVALUE {
            get {
                return this.aTVVALUEField;
            }
            set {
                this.aTVVALUEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string s1P1DUTY {
            get {
                return this.s1P1DUTYField;
            }
            set {
                this.s1P1DUTYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string s1P2ACODE {
            get {
                return this.s1P2ACODEField;
            }
            set {
                this.s1P2ACODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string s1P2ADUTY {
            get {
                return this.s1P2ADUTYField;
            }
            set {
                this.s1P2ADUTYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string s1P2BDUTY {
            get {
                return this.s1P2BDUTYField;
            }
            set {
                this.s1P2BDUTYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string s1P3ACODE {
            get {
                return this.s1P3ACODEField;
            }
            set {
                this.s1P3ACODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string s1P3ADUTY {
            get {
                return this.s1P3ADUTYField;
            }
            set {
                this.s1P3ADUTYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string s1P3BCODE {
            get {
                return this.s1P3BCODEField;
            }
            set {
                this.s1P3BCODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string s1P3BDUTY {
            get {
                return this.s1P3BDUTYField;
            }
            set {
                this.s1P3BDUTYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string s1P3CCODE {
            get {
                return this.s1P3CCODEField;
            }
            set {
                this.s1P3CCODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string s1P3CDUTY {
            get {
                return this.s1P3CDUTYField;
            }
            set {
                this.s1P3CDUTYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string s1P3DCODE {
            get {
                return this.s1P3DCODEField;
            }
            set {
                this.s1P3DCODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string s1P3DDUTY {
            get {
                return this.s1P3DDUTYField;
            }
            set {
                this.s1P3DDUTYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string s1P5ADUTY {
            get {
                return this.s1P5ADUTYField;
            }
            set {
                this.s1P5ADUTYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string s1P5BDUTY {
            get {
                return this.s1P5BDUTYField;
            }
            set {
                this.s1P5BDUTYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string s2P1DUTY {
            get {
                return this.s2P1DUTYField;
            }
            set {
                this.s2P1DUTYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string s2P1DUTYCODE {
            get {
                return this.s2P1DUTYCODEField;
            }
            set {
                this.s2P1DUTYCODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string s2P2DUTY {
            get {
                return this.s2P2DUTYField;
            }
            set {
                this.s2P2DUTYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string s2P2DUTYCODE {
            get {
                return this.s2P2DUTYCODEField;
            }
            set {
                this.s2P2DUTYCODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string s2P3DUTY {
            get {
                return this.s2P3DUTYField;
            }
            set {
                this.s2P3DUTYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string s2P3DUTYCODE {
            get {
                return this.s2P3DUTYCODEField;
            }
            set {
                this.s2P3DUTYCODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SUCCES {
            get {
                return this.sUCCESField;
            }
            set {
                this.sUCCESField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TOTALDUE {
            get {
                return this.tOTALDUEField;
            }
            set {
                this.tOTALDUEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TOTALDUTIES {
            get {
                return this.tOTALDUTIESField;
            }
            set {
                this.tOTALDUTIESField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string VATVALUE {
            get {
                return this.vATVALUEField;
            }
            set {
                this.vATVALUEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string WCUSVAL {
            get {
                return this.wCUSVALField;
            }
            set {
                this.wCUSVALField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18033")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.cc.com/")]
    public partial class dccl9010 {
        
        private string aDDINFOField;
        
        private string aNDORField;
        
        private string cENTSPERUNITField;
        
        private string dISCOUNTPERCField;
        
        private string dUTYPERCField;
        
        private string hIGHLOWField;
        
        private string s1P2BCODEField;
        
        private string s1P2BFLAGField;
        
        private string s1P2BPERCField;
        
        private string sPECIALField;
        
        private string tARIFFField;
        
        private string tARTYPEField;
        
        private string tEXTILEField;
        
        private string uNIT1Field;
        
        private string uNIT2Field;
        
        private string uNIT3Field;
        
        private string uNITFACTORField;
        
        private string uNITPOINTERField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ADDINFO {
            get {
                return this.aDDINFOField;
            }
            set {
                this.aDDINFOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ANDOR {
            get {
                return this.aNDORField;
            }
            set {
                this.aNDORField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CENTSPERUNIT {
            get {
                return this.cENTSPERUNITField;
            }
            set {
                this.cENTSPERUNITField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DISCOUNTPERC {
            get {
                return this.dISCOUNTPERCField;
            }
            set {
                this.dISCOUNTPERCField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DUTYPERC {
            get {
                return this.dUTYPERCField;
            }
            set {
                this.dUTYPERCField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string HIGHLOW {
            get {
                return this.hIGHLOWField;
            }
            set {
                this.hIGHLOWField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string s1P2BCODE {
            get {
                return this.s1P2BCODEField;
            }
            set {
                this.s1P2BCODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string s1P2BFLAG {
            get {
                return this.s1P2BFLAGField;
            }
            set {
                this.s1P2BFLAGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string s1P2BPERC {
            get {
                return this.s1P2BPERCField;
            }
            set {
                this.s1P2BPERCField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SPECIAL {
            get {
                return this.sPECIALField;
            }
            set {
                this.sPECIALField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TARIFF {
            get {
                return this.tARIFFField;
            }
            set {
                this.tARIFFField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TARTYPE {
            get {
                return this.tARTYPEField;
            }
            set {
                this.tARTYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TEXTILE {
            get {
                return this.tEXTILEField;
            }
            set {
                this.tEXTILEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string UNIT1 {
            get {
                return this.uNIT1Field;
            }
            set {
                this.uNIT1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string UNIT2 {
            get {
                return this.uNIT2Field;
            }
            set {
                this.uNIT2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string UNIT3 {
            get {
                return this.uNIT3Field;
            }
            set {
                this.uNIT3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string UNITFACTOR {
            get {
                return this.uNITFACTORField;
            }
            set {
                this.uNITFACTORField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string UNITPOINTER {
            get {
                return this.uNITPOINTERField;
            }
            set {
                this.uNITPOINTERField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18033")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.cc.com/")]
    public partial class dccl9010V {
        
        private string aPPLYS1P2BField;
        
        private string oRIGINField;
        
        private string wFACTORField;
        
        private string wFORVALField;
        
        private string wQTY1Field;
        
        private string wQTY2Field;
        
        private string wQTY3Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string APPLYS1P2B {
            get {
                return this.aPPLYS1P2BField;
            }
            set {
                this.aPPLYS1P2BField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ORIGIN {
            get {
                return this.oRIGINField;
            }
            set {
                this.oRIGINField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string WFACTOR {
            get {
                return this.wFACTORField;
            }
            set {
                this.wFACTORField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string WFORVAL {
            get {
                return this.wFORVALField;
            }
            set {
                this.wFORVALField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string WQTY1 {
            get {
                return this.wQTY1Field;
            }
            set {
                this.wQTY1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string WQTY2 {
            get {
                return this.wQTY2Field;
            }
            set {
                this.wQTY2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string WQTY3 {
            get {
                return this.wQTY3Field;
            }
            set {
                this.wQTY3Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void callCCL9010CompletedEventHandler(object sender, callCCL9010CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class callCCL9010CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal callCCL9010CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ccl9010 Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ccl9010)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void callProgramCompletedEventHandler(object sender, callProgramCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class callProgramCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal callProgramCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public programCallResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((programCallResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void getPcmlDocumentCompletedEventHandler(object sender, getPcmlDocumentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getPcmlDocumentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getPcmlDocumentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public programCallResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((programCallResult)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591