//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VVExchangeWCF
{
    using System.Runtime.Serialization;


    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ImportMessageModel", Namespace = "http://schemas.datacontract.org/2004/07/VVExchangeWCF")]
    public partial class ImportMessageModel : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private System.Nullable<System.DateTime> MessageDTField;

        private System.Nullable<long> MessageIDField;

        private System.Nullable<int> MaxRowsField;

        private System.Nullable<byte> ProfileIDField;

        private string XMLMessageField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> MaxRows
        {
            get
            {
                return this.MaxRowsField;
            }
            set
            {
                this.MaxRowsField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> MessageDT
        {
            get
            {
                return this.MessageDTField;
            }
            set
            {
                this.MessageDTField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> MessageID
        {
            get
            {
                return this.MessageIDField;
            }
            set
            {
                this.MessageIDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<byte> ProfileID
        {
            get
            {
                return this.ProfileIDField;
            }
            set
            {
                this.ProfileIDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string XMLMessage
        {
            get
            {
                return this.XMLMessageField;
            }
            set
            {
                this.XMLMessageField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName = "IService")]
public interface IService
{

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IService/GetData", ReplyAction = "http://tempuri.org/IService/GetDataResponse")]
    string GetData(string value);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IService/GetMessages", ReplyAction = "http://tempuri.org/IService/GetMessagesResponse")]
    bool GetMessages(System.Nullable<byte> profileID, System.Nullable<System.DateTime> messageDT, System.Nullable<int> maxRows, ref VVExchangeWCF.ImportMessageModel[] importMessageModel, ref string msg);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IServiceChannel : IService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class ServiceClient : System.ServiceModel.ClientBase<IService>, IService
{

    public ServiceClient()
    {
    }

    public ServiceClient(string endpointConfigurationName) :
        base(endpointConfigurationName)
    {
    }

    public ServiceClient(string endpointConfigurationName, string remoteAddress) :
        base(endpointConfigurationName, remoteAddress)
    {
    }

    public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
        base(endpointConfigurationName, remoteAddress)
    {
    }

    public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
        base(binding, remoteAddress)
    {
    }

    public string GetData(string value)
    {
        return base.Channel.GetData(value);
    }

    public bool GetMessages(System.Nullable<byte> profileID, System.Nullable<System.DateTime> messageDT, System.Nullable<int> maxRows, ref VVExchangeWCF.ImportMessageModel[] importMessageModel, ref string msg)
    {
        return base.Channel.GetMessages(profileID, messageDT, maxRows, ref importMessageModel, ref msg);
    }
}
